<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MotorKu</name>
   <tag></tag>
   <elementGuidId>3ad2ac5c-ef07-4934-8ab0-b4f949d4c0f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-nav-main']/div/div/ul/li[2]/div/ul/li/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.is-child > ul > li.has-child > div.is-child > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f38c4a4-6624-49cc-aab5-17e4bfae56ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/motorku</value>
      <webElementGuid>d97fbc87-fb54-4f4e-906f-2112a2e58c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                MotorKu
                                                            </value>
      <webElementGuid>01321e67-b00a-4879-b34f-fc8e27fb2ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-nav-main&quot;)/div[@class=&quot;row g-0 justify-content-between&quot;]/div[@class=&quot;col-12 col-xl-auto col-left&quot;]/ul[@class=&quot;nav drop-menu&quot;]/li[@class=&quot;has-child&quot;]/div[@class=&quot;is-child&quot;]/ul[1]/li[@class=&quot;has-child&quot;]/div[@class=&quot;is-child&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>398eee7b-d9f7-4e0d-9466-a00b063903f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-nav-main']/div/div/ul/li[2]/div/ul/li/div/ul/li/a</value>
      <webElementGuid>70e0a936-601c-4e97-97b3-3cf5f322f6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembiayaan Multiguna'])[1]/following::a[1]</value>
      <webElementGuid>92e1a1bf-6e23-46ae-afc7-fa5b0bc379da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::a[2]</value>
      <webElementGuid>582e4607-c30e-4fbb-ae45-87b11c89642c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MobilKu'])[1]/preceding::a[1]</value>
      <webElementGuid>da0d2a6a-85d2-4e46-9568-1bd5246089a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/motorku')]</value>
      <webElementGuid>87127724-6384-4965-ab50-bac6d03c243f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/div/ul/li/a</value>
      <webElementGuid>64f73777-3298-4ed0-abab-f310801f40dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/motorku' and (text() = '
                                                                MotorKu
                                                            ' or . = '
                                                                MotorKu
                                                            ')]</value>
      <webElementGuid>c273cfdd-61af-4398-bc20-37449e2114fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
