<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HEMASKUARTIKEL</name>
   <tag></tag>
   <elementGuidId>15b9d8d9-520c-4b86-9597-6b6497b1190e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='post-section']/div[2]/div/div/div/article/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>29ab0a3f-ffb8-4794-b90c-4e4261bf9400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MASKu adalah layanan pembiayaan logam mulia (emas) 24K kepada masyarakat secara cicilan/kredit. MASKu hadir sebagai solusi dalam rangka membantu dan memudahkan masyarakat untuk memiliki logam mulia (emas) yang aman dan terpercaya.</value>
      <webElementGuid>9564138f-077e-41a0-8a9b-c48ac4ebc41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-section&quot;)/div[@class=&quot;container-lg&quot;]/div[@class=&quot;row align-items-start&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;desc aos-init aos-animate&quot;]/article[@class=&quot;text-primary&quot;]/p[2]</value>
      <webElementGuid>308dde9d-5925-42e8-a695-7db1cb0b0f45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='post-section']/div[2]/div/div/div/article/p[2]</value>
      <webElementGuid>f354bd73-fc30-4ae0-b9f8-e34f5a4c6a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MASKu'])[3]/following::p[2]</value>
      <webElementGuid>f31e20e3-83ef-4e44-b383-c1ae7313ef93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MASKu'])[2]/following::p[2]</value>
      <webElementGuid>a945284f-97aa-457f-8298-685f6899ea74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEUNGGULAN MASKu'])[1]/preceding::p[2]</value>
      <webElementGuid>2ec07af0-c36d-41f7-ac12-d895d96e4c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JUJUR'])[1]/preceding::p[3]</value>
      <webElementGuid>9866461c-279e-4b3d-9172-318c4a8ad846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MASKu adalah layanan pembiayaan logam mulia (emas) 24K kepada masyarakat secara cicilan/kredit. MASKu hadir sebagai solusi dalam rangka membantu dan memudahkan masyarakat untuk memiliki logam mulia (emas) yang aman dan terpercaya.']/parent::*</value>
      <webElementGuid>e3048182-f7a4-4d24-86fe-f360c4abc8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>7af02f73-976a-4839-a483-ee793dba4f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'MASKu adalah layanan pembiayaan logam mulia (emas) 24K kepada masyarakat secara cicilan/kredit. MASKu hadir sebagai solusi dalam rangka membantu dan memudahkan masyarakat untuk memiliki logam mulia (emas) yang aman dan terpercaya.' or . = 'MASKu adalah layanan pembiayaan logam mulia (emas) 24K kepada masyarakat secara cicilan/kredit. MASKu hadir sebagai solusi dalam rangka membantu dan memudahkan masyarakat untuk memiliki logam mulia (emas) yang aman dan terpercaya.')]</value>
      <webElementGuid>64f52fd4-81a2-4dd1-87bf-c26b91224912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
